# Generated by Django 3.2.14 on 2022-07-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagetitle', models.CharField(max_length=200)),
                ('analysisimage', models.ImageField(upload_to='analysisImages/')),
            ],
        ),
    ]
