# Generated by Django 3.2.13 on 2022-07-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imagefile',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='leukemiaImages/'),
            preserve_default=False,
        ),
    ]
