# Generated by Django 3.2.13 on 2022-07-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0002_auto_20220702_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='imageFiled',
        ),
    ]
