# Generated by Django 3.2.13 on 2022-07-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0004_image_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageUrl',
        ),
    ]
