# Generated by Django 3.2.13 on 2022-07-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0006_image_namefiled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageFiled',
        ),
    ]
