# Generated by Django 3.2.13 on 2022-07-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0007_remove_image_imagefiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageFiled',
            field=models.ImageField(blank=True, null=True, upload_to='leukemiaImages/'),
        ),
    ]
