# Generated by Django 3.2.14 on 2022-07-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0008_image_imagefiled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='namefiled',
        ),
        migrations.AlterField(
            model_name='image',
            name='imageFiled',
            field=models.ImageField(upload_to='leukemiaImages/'),
        ),
    ]
