# Generated by Django 3.2.14 on 2022-07-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0009_auto_20220704_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeukemiaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leukemiaimage', models.ImageField(upload_to='leukemiaImages/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
