# Generated by Django 3.2.14 on 2022-07-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0010_auto_20220717_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='leukemiaimage',
            name='imagetitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
